version: "2"
run:
  concurrency: 8
  issues-exit-code: 1
  tests: true
output:
  formats: 
    text: 
      print-issued-lines: true
      print-linter-name: true
linters:
  default: none
  enable:
    - errcheck
    - goconst
    - gosec
    - govet
    - ineffassign
    # - revive
    - staticcheck
    - unused
  settings:
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: G104
      - path: (.+)\.go$
        text: exported func .* returns unexported type .*, which can be annoying to use
      - path: (.+)\.go$
        text: should have a package comment
      - path: (.+)\.go$
        text: don't use an underscore in package name
formatters:
  enable:
    - goimports
exclusions:
  generated: lax
  paths:
    # Add chmod 777 to the data directory so that the linter can access it
    - data
    - .cache
    - third_party$
    - builtin$
    - examples$