package logs

import (
	"time"

	"github.com/chistyakoviv/logbot/internal/model"
)

type LogsRow struct {
	Id            int       `db:"id"`
	Token         string    `db:"token"`
	Data          string    `db:"data"`
	Service       string    `db:"service"`
	ContainerName string    `db:"container_name"`
	ContainerId   string    `db:"container_id"`
	Node          string    `db:"node"`
	NodeId        string    `db:"node_id"`
	Hash          string    `db:"hash"`
	CreatedAt     time.Time `db:"created_at"`
}

func (r *LogsRow) Values() []any {
	return []any{
		// Id is generated by the database
		// r.Id,
		r.Token,
		r.Data,
		r.Service,
		r.ContainerName,
		r.ContainerId,
		r.Node,
		r.NodeId,
		r.Hash,
		r.CreatedAt,
	}
}

func ToModel(r *LogsRow) *model.Log {
	if r == nil {
		return nil
	}
	return &model.Log{
		Id:            r.Id,
		Token:         r.Token,
		Data:          r.Data,
		Service:       r.Service,
		ContainerName: r.ContainerName,
		ContainerId:   r.ContainerId,
		Node:          r.Node,
		NodeId:        r.NodeId,
		Hash:          r.Hash,
		CreatedAt:     r.CreatedAt,
	}
}

func FromModel(m *model.Log) LogsRow {
	if m == nil {
		return LogsRow{}
	}
	return LogsRow{
		Id:            m.Id,
		Token:         m.Token,
		Data:          m.Data,
		Service:       m.Service,
		ContainerName: m.ContainerName,
		ContainerId:   m.ContainerId,
		Node:          m.Node,
		NodeId:        m.NodeId,
		Hash:          m.Hash,
		CreatedAt:     m.CreatedAt,
	}
}
