package logs

const logsTable = "logs"

const (
	logsTableColumnId         = "id"
	logsTableColumnToken      = "token"
	logsTableColumnData       = "data"
	logsTableColumnLabel      = "label"
	logsTableColumnHash       = "hash"
	logsTableColumnCreateddAt = "created_at"
)

var logsTableInsertableColumns = []string{
	// Do not include id as it is a primary key generated by the database
	// logsTableColumnId,
	logsTableColumnToken,
	logsTableColumnData,
	logsTableColumnLabel,
	logsTableColumnHash,
	logsTableColumnCreateddAt,
}

var logsTableColumns = []string{
	logsTableColumnId,
	logsTableColumnToken,
	logsTableColumnData,
	logsTableColumnLabel,
	logsTableColumnHash,
	logsTableColumnCreateddAt,
}
