package logs

const logsTable = "logs"

const (
	logsTableColumnId            = "id"
	logsTableColumnToken         = "token"
	logsTableColumnData          = "data"
	logsTableColumnService       = "service"
	logsTableColumnContainerName = "container_name"
	logsTableColumnContainerId   = "container_id"
	logsTableColumnNode          = "node"
	logsTableColumnNodeId        = "node_id"
	logsTableColumnHash          = "hash"
	logsTableColumnCreatedAt     = "created_at"
)

var logsTableInsertableColumns = []string{
	// Do not include id as it is a primary key generated by the database
	// logsTableColumnId,
	logsTableColumnToken,
	logsTableColumnData,
	logsTableColumnService,
	logsTableColumnContainerName,
	logsTableColumnContainerId,
	logsTableColumnNode,
	logsTableColumnNodeId,
	logsTableColumnHash,
	logsTableColumnCreatedAt,
}

var logsTableColumns = []string{
	logsTableColumnId,
	logsTableColumnToken,
	logsTableColumnData,
	logsTableColumnService,
	logsTableColumnContainerName,
	logsTableColumnContainerId,
	logsTableColumnNode,
	logsTableColumnNodeId,
	logsTableColumnHash,
	logsTableColumnCreatedAt,
}
