FROM golang:1.26.1-alpine3.22

# Do not use MOCKERY_VERSION, as it causes mockery to fail with the version parsing error.
ENV MOCKERY_INSTALL_VERSION=3.5.5
ENV GOLANGCI_LINT_VERSION=2.11.2

RUN apk add --no-cache \
    curl \
    make \
    git \
    bash \
    postgresql-client

RUN mkdir -p /tmp/mockery && \
    curl -L -o /tmp/mockery/mockery.tar.gz "https://github.com/vektra/mockery/releases/download/v${MOCKERY_INSTALL_VERSION}/mockery_${MOCKERY_INSTALL_VERSION}_Linux_x86_64.tar.gz" && \
    tar -xzf /tmp/mockery/mockery.tar.gz -C /tmp/mockery && \
    mv /tmp/mockery/mockery /usr/local/bin/ && \
    chmod +x /usr/local/bin/mockery && \
    rm -rf /tmp/mockery

# See https://golangci-lint.run/welcome/install/
RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v${GOLANGCI_LINT_VERSION}

WORKDIR /go/src/github.com/chistyakoviv/logbot

RUN go install github.com/pressly/goose/v3/cmd/goose@v3.26.0

COPY ./go.mod ./go.sum ./
RUN go mod download

COPY ./docker/common/wait-for-it.sh /usr/local/bin/wait-for-it
RUN chmod 555 /usr/local/bin/wait-for-it

ARG UID=1000
ARG GID=1000

RUN addgroup -g "${GID}" app && adduser -u "${UID}" -G app -s /bin/sh -D app
RUN chown -R app:app /go/pkg

USER app